version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install all dependencies (including dependencies for running tests)
      # - npm install -g aws-cdk@1.160.0
      # - npm install -g aws-cdk
      - npm install -g @nestjs/cli
      - npm install
      # Discover and run unit tests in the '__tests__' directory
      # - npm run test
  # pre_build:
  #   commands:
  #     # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
  #     - npm prune --production
  #     # Copy artifacts to a separate folder
  #     - mkdir function-code
  #     - cp -r src node_modules function-code
  build:
    commands:
      - npm run-script build
  post_build:
    commands: 
      - aws s3 cp dist s3://$S3_BUCKET/$CODEBUILD_BUILD_ID/ --recursive --acl public-read
      # - aws s3 cp dist s3://$S3_BUCKET/$CODEBUILD_BUILD_ID/
# artifacts:
#   files:
#     - template-export.yml
