version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @nestjs/cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
  post_build:
    commands: 
      - aws s3 cp dist s3://$S3_BUCKET/$CODEBUILD_BUILD_ID/ --recursive --acl public-read
      # - aws s3 cp dist s3://$S3_BUCKET/$CODEBUILD_BUILD_ID/
# artifacts:
#   files:
#     - template-export.yml
artifacts:
  files:
    - src/**/*
    - package.json
    - node_modules/**/*
